# Generated by Django 4.0.4 on 2022-05-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('artiste', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Musique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('artiste', models.CharField(max_length=100)),
                ('date_parution', models.DateField(blank=True, null=True)),
                ('min', models.IntegerField()),
                ('sec', models.IntegerField()),
                ('commentaire', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
